<?php
namespace EDDAmazon\Vendor\Aws;

/**
 * Builds AWS clients based on configuration settings.
 *
 * @method \EDDAmazon\Vendor\Aws\ACMPCA\ACMPCAClient createACMPCA(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionACMPCA(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ARCZonalShift\ARCZonalShiftClient createARCZonalShift(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionARCZonalShift(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AccessAnalyzer\AccessAnalyzerClient createAccessAnalyzer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAccessAnalyzer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Account\AccountClient createAccount(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAccount(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Acm\AcmClient createAcm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAcm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AlexaForBusiness\AlexaForBusinessClient createAlexaForBusiness(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAlexaForBusiness(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Amplify\AmplifyClient createAmplify(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAmplify(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AmplifyBackend\AmplifyBackendClient createAmplifyBackend(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAmplifyBackend(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AmplifyUIBuilder\AmplifyUIBuilderClient createAmplifyUIBuilder(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAmplifyUIBuilder(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ApiGateway\ApiGatewayClient createApiGateway(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionApiGateway(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ApiGatewayManagementApi\ApiGatewayManagementApiClient createApiGatewayManagementApi(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionApiGatewayManagementApi(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ApiGatewayV2\ApiGatewayV2Client createApiGatewayV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionApiGatewayV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppConfig\AppConfigClient createAppConfig(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppConfig(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppConfigData\AppConfigDataClient createAppConfigData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppConfigData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppFabric\AppFabricClient createAppFabric(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppFabric(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppIntegrationsService\AppIntegrationsServiceClient createAppIntegrationsService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppIntegrationsService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppMesh\AppMeshClient createAppMesh(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppMesh(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppRegistry\AppRegistryClient createAppRegistry(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppRegistry(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppRunner\AppRunnerClient createAppRunner(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppRunner(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AppSync\AppSyncClient createAppSync(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppSync(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Appflow\AppflowClient createAppflow(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppflow(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ApplicationAutoScaling\ApplicationAutoScalingClient createApplicationAutoScaling(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionApplicationAutoScaling(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ApplicationCostProfiler\ApplicationCostProfilerClient createApplicationCostProfiler(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionApplicationCostProfiler(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ApplicationDiscoveryService\ApplicationDiscoveryServiceClient createApplicationDiscoveryService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionApplicationDiscoveryService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ApplicationInsights\ApplicationInsightsClient createApplicationInsights(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionApplicationInsights(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Appstream\AppstreamClient createAppstream(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAppstream(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Athena\AthenaClient createAthena(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAthena(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AuditManager\AuditManagerClient createAuditManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAuditManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AugmentedAIRuntime\AugmentedAIRuntimeClient createAugmentedAIRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAugmentedAIRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AutoScaling\AutoScalingClient createAutoScaling(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAutoScaling(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\AutoScalingPlans\AutoScalingPlansClient createAutoScalingPlans(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionAutoScalingPlans(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Backup\BackupClient createBackup(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBackup(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\BackupGateway\BackupGatewayClient createBackupGateway(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBackupGateway(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\BackupStorage\BackupStorageClient createBackupStorage(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBackupStorage(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Batch\BatchClient createBatch(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBatch(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Bedrock\BedrockClient createBedrock(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBedrock(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\BedrockRuntime\BedrockRuntimeClient createBedrockRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBedrockRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\BillingConductor\BillingConductorClient createBillingConductor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBillingConductor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Braket\BraketClient createBraket(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBraket(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Budgets\BudgetsClient createBudgets(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionBudgets(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Chime\ChimeClient createChime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionChime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ChimeSDKIdentity\ChimeSDKIdentityClient createChimeSDKIdentity(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionChimeSDKIdentity(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ChimeSDKMediaPipelines\ChimeSDKMediaPipelinesClient createChimeSDKMediaPipelines(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionChimeSDKMediaPipelines(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ChimeSDKMeetings\ChimeSDKMeetingsClient createChimeSDKMeetings(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionChimeSDKMeetings(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ChimeSDKMessaging\ChimeSDKMessagingClient createChimeSDKMessaging(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionChimeSDKMessaging(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ChimeSDKVoice\ChimeSDKVoiceClient createChimeSDKVoice(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionChimeSDKVoice(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CleanRooms\CleanRoomsClient createCleanRooms(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCleanRooms(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Cloud9\Cloud9Client createCloud9(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloud9(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudControlApi\CloudControlApiClient createCloudControlApi(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudControlApi(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudDirectory\CloudDirectoryClient createCloudDirectory(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudDirectory(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudFormation\CloudFormationClient createCloudFormation(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudFormation(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudFront\CloudFrontClient createCloudFront(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudFront(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudHSMV2\CloudHSMV2Client createCloudHSMV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudHSMV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudHsm\CloudHsmClient createCloudHsm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudHsm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudSearch\CloudSearchClient createCloudSearch(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudSearch(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudSearchDomain\CloudSearchDomainClient createCloudSearchDomain(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudSearchDomain(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudTrail\CloudTrailClient createCloudTrail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudTrail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudTrailData\CloudTrailDataClient createCloudTrailData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudTrailData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudWatch\CloudWatchClient createCloudWatch(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudWatch(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudWatchEvents\CloudWatchEventsClient createCloudWatchEvents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudWatchEvents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudWatchEvidently\CloudWatchEvidentlyClient createCloudWatchEvidently(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudWatchEvidently(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudWatchLogs\CloudWatchLogsClient createCloudWatchLogs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudWatchLogs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CloudWatchRUM\CloudWatchRUMClient createCloudWatchRUM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCloudWatchRUM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeArtifact\CodeArtifactClient createCodeArtifact(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeArtifact(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeBuild\CodeBuildClient createCodeBuild(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeBuild(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeCatalyst\CodeCatalystClient createCodeCatalyst(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeCatalyst(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeCommit\CodeCommitClient createCodeCommit(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeCommit(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeDeploy\CodeDeployClient createCodeDeploy(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeDeploy(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeGuruProfiler\CodeGuruProfilerClient createCodeGuruProfiler(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeGuruProfiler(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeGuruReviewer\CodeGuruReviewerClient createCodeGuruReviewer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeGuruReviewer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeGuruSecurity\CodeGuruSecurityClient createCodeGuruSecurity(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeGuruSecurity(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodePipeline\CodePipelineClient createCodePipeline(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodePipeline(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeStar\CodeStarClient createCodeStar(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeStar(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeStarNotifications\CodeStarNotificationsClient createCodeStarNotifications(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeStarNotifications(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CodeStarconnections\CodeStarconnectionsClient createCodeStarconnections(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCodeStarconnections(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CognitoIdentity\CognitoIdentityClient createCognitoIdentity(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCognitoIdentity(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CognitoIdentityProvider\CognitoIdentityProviderClient createCognitoIdentityProvider(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCognitoIdentityProvider(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CognitoSync\CognitoSyncClient createCognitoSync(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCognitoSync(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Comprehend\ComprehendClient createComprehend(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionComprehend(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ComprehendMedical\ComprehendMedicalClient createComprehendMedical(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionComprehendMedical(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ComputeOptimizer\ComputeOptimizerClient createComputeOptimizer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionComputeOptimizer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ConfigService\ConfigServiceClient createConfigService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionConfigService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Connect\ConnectClient createConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ConnectCampaignService\ConnectCampaignServiceClient createConnectCampaignService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionConnectCampaignService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ConnectCases\ConnectCasesClient createConnectCases(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionConnectCases(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ConnectContactLens\ConnectContactLensClient createConnectContactLens(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionConnectContactLens(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ConnectParticipant\ConnectParticipantClient createConnectParticipant(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionConnectParticipant(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ConnectWisdomService\ConnectWisdomServiceClient createConnectWisdomService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionConnectWisdomService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ControlTower\ControlTowerClient createControlTower(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionControlTower(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CostExplorer\CostExplorerClient createCostExplorer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCostExplorer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CostandUsageReportService\CostandUsageReportServiceClient createCostandUsageReportService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCostandUsageReportService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\CustomerProfiles\CustomerProfilesClient createCustomerProfiles(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionCustomerProfiles(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DAX\DAXClient createDAX(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDAX(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DLM\DLMClient createDLM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDLM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DataExchange\DataExchangeClient createDataExchange(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDataExchange(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DataPipeline\DataPipelineClient createDataPipeline(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDataPipeline(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DataSync\DataSyncClient createDataSync(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDataSync(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DataZone\DataZoneClient createDataZone(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDataZone(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DatabaseMigrationService\DatabaseMigrationServiceClient createDatabaseMigrationService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDatabaseMigrationService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Detective\DetectiveClient createDetective(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDetective(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DevOpsGuru\DevOpsGuruClient createDevOpsGuru(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDevOpsGuru(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DeviceFarm\DeviceFarmClient createDeviceFarm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDeviceFarm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DirectConnect\DirectConnectClient createDirectConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDirectConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DirectoryService\DirectoryServiceClient createDirectoryService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDirectoryService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DocDB\DocDBClient createDocDB(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDocDB(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DocDBElastic\DocDBElasticClient createDocDBElastic(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDocDBElastic(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DynamoDb\DynamoDbClient createDynamoDb(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDynamoDb(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\DynamoDbStreams\DynamoDbStreamsClient createDynamoDbStreams(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionDynamoDbStreams(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\EBS\EBSClient createEBS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEBS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\EC2InstanceConnect\EC2InstanceConnectClient createEC2InstanceConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEC2InstanceConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ECRPublic\ECRPublicClient createECRPublic(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionECRPublic(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\EKS\EKSClient createEKS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEKS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\EMRContainers\EMRContainersClient createEMRContainers(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEMRContainers(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\EMRServerless\EMRServerlessClient createEMRServerless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEMRServerless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Ec2\Ec2Client createEc2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEc2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Ecr\EcrClient createEcr(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEcr(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Ecs\EcsClient createEcs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEcs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Efs\EfsClient createEfs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEfs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ElastiCache\ElastiCacheClient createElastiCache(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionElastiCache(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ElasticBeanstalk\ElasticBeanstalkClient createElasticBeanstalk(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionElasticBeanstalk(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ElasticInference\ElasticInferenceClient createElasticInference(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionElasticInference(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ElasticLoadBalancing\ElasticLoadBalancingClient createElasticLoadBalancing(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionElasticLoadBalancing(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ElasticLoadBalancingV2\ElasticLoadBalancingV2Client createElasticLoadBalancingV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionElasticLoadBalancingV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ElasticTranscoder\ElasticTranscoderClient createElasticTranscoder(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionElasticTranscoder(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ElasticsearchService\ElasticsearchServiceClient createElasticsearchService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionElasticsearchService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Emr\EmrClient createEmr(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEmr(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\EntityResolution\EntityResolutionClient createEntityResolution(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEntityResolution(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\EventBridge\EventBridgeClient createEventBridge(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionEventBridge(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\FIS\FISClient createFIS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionFIS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\FMS\FMSClient createFMS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionFMS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\FSx\FSxClient createFSx(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionFSx(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\FinSpaceData\FinSpaceDataClient createFinSpaceData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionFinSpaceData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Firehose\FirehoseClient createFirehose(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionFirehose(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ForecastQueryService\ForecastQueryServiceClient createForecastQueryService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionForecastQueryService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ForecastService\ForecastServiceClient createForecastService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionForecastService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\FraudDetector\FraudDetectorClient createFraudDetector(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionFraudDetector(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\GameLift\GameLiftClient createGameLift(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGameLift(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Glacier\GlacierClient createGlacier(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGlacier(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\GlobalAccelerator\GlobalAcceleratorClient createGlobalAccelerator(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGlobalAccelerator(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Glue\GlueClient createGlue(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGlue(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\GlueDataBrew\GlueDataBrewClient createGlueDataBrew(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGlueDataBrew(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Greengrass\GreengrassClient createGreengrass(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGreengrass(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\GreengrassV2\GreengrassV2Client createGreengrassV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGreengrassV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\GroundStation\GroundStationClient createGroundStation(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGroundStation(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\GuardDuty\GuardDutyClient createGuardDuty(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionGuardDuty(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Health\HealthClient createHealth(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionHealth(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\HealthLake\HealthLakeClient createHealthLake(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionHealthLake(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Honeycode\HoneycodeClient createHoneycode(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionHoneycode(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IVS\IVSClient createIVS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIVS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IVSRealTime\IVSRealTimeClient createIVSRealTime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIVSRealTime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Iam\IamClient createIam(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIam(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IdentityStore\IdentityStoreClient createIdentityStore(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIdentityStore(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ImportExport\ImportExportClient createImportExport(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionImportExport(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Inspector\InspectorClient createInspector(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionInspector(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Inspector2\Inspector2Client createInspector2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionInspector2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\InternetMonitor\InternetMonitorClient createInternetMonitor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionInternetMonitor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoT1ClickDevicesService\IoT1ClickDevicesServiceClient createIoT1ClickDevicesService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoT1ClickDevicesService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoT1ClickProjects\IoT1ClickProjectsClient createIoT1ClickProjects(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoT1ClickProjects(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTAnalytics\IoTAnalyticsClient createIoTAnalytics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTAnalytics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTDeviceAdvisor\IoTDeviceAdvisorClient createIoTDeviceAdvisor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTDeviceAdvisor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTEvents\IoTEventsClient createIoTEvents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTEvents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTEventsData\IoTEventsDataClient createIoTEventsData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTEventsData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTFleetHub\IoTFleetHubClient createIoTFleetHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTFleetHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTFleetWise\IoTFleetWiseClient createIoTFleetWise(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTFleetWise(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTJobsDataPlane\IoTJobsDataPlaneClient createIoTJobsDataPlane(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTJobsDataPlane(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTRoboRunner\IoTRoboRunnerClient createIoTRoboRunner(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTRoboRunner(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTSecureTunneling\IoTSecureTunnelingClient createIoTSecureTunneling(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTSecureTunneling(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTSiteWise\IoTSiteWiseClient createIoTSiteWise(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTSiteWise(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTThingsGraph\IoTThingsGraphClient createIoTThingsGraph(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTThingsGraph(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTTwinMaker\IoTTwinMakerClient createIoTTwinMaker(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTTwinMaker(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IoTWireless\IoTWirelessClient createIoTWireless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIoTWireless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Iot\IotClient createIot(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIot(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\IotDataPlane\IotDataPlaneClient createIotDataPlane(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionIotDataPlane(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Kafka\KafkaClient createKafka(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKafka(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KafkaConnect\KafkaConnectClient createKafkaConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKafkaConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KendraRanking\KendraRankingClient createKendraRanking(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKendraRanking(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Keyspaces\KeyspacesClient createKeyspaces(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKeyspaces(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Kinesis\KinesisClient createKinesis(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesis(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KinesisAnalytics\KinesisAnalyticsClient createKinesisAnalytics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesisAnalytics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KinesisAnalyticsV2\KinesisAnalyticsV2Client createKinesisAnalyticsV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesisAnalyticsV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KinesisVideo\KinesisVideoClient createKinesisVideo(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesisVideo(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KinesisVideoArchivedMedia\KinesisVideoArchivedMediaClient createKinesisVideoArchivedMedia(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesisVideoArchivedMedia(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KinesisVideoMedia\KinesisVideoMediaClient createKinesisVideoMedia(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesisVideoMedia(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KinesisVideoSignalingChannels\KinesisVideoSignalingChannelsClient createKinesisVideoSignalingChannels(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesisVideoSignalingChannels(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\KinesisVideoWebRTCStorage\KinesisVideoWebRTCStorageClient createKinesisVideoWebRTCStorage(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKinesisVideoWebRTCStorage(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Kms\KmsClient createKms(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionKms(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LakeFormation\LakeFormationClient createLakeFormation(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLakeFormation(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Lambda\LambdaClient createLambda(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLambda(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LaunchWizard\LaunchWizardClient createLaunchWizard(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLaunchWizard(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LexModelBuildingService\LexModelBuildingServiceClient createLexModelBuildingService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLexModelBuildingService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LexModelsV2\LexModelsV2Client createLexModelsV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLexModelsV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LexRuntimeService\LexRuntimeServiceClient createLexRuntimeService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLexRuntimeService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LexRuntimeV2\LexRuntimeV2Client createLexRuntimeV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLexRuntimeV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LicenseManager\LicenseManagerClient createLicenseManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLicenseManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LicenseManagerLinuxSubscriptions\LicenseManagerLinuxSubscriptionsClient createLicenseManagerLinuxSubscriptions(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLicenseManagerLinuxSubscriptions(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LicenseManagerUserSubscriptions\LicenseManagerUserSubscriptionsClient createLicenseManagerUserSubscriptions(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLicenseManagerUserSubscriptions(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Lightsail\LightsailClient createLightsail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLightsail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LocationService\LocationServiceClient createLocationService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLocationService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LookoutEquipment\LookoutEquipmentClient createLookoutEquipment(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLookoutEquipment(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LookoutMetrics\LookoutMetricsClient createLookoutMetrics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLookoutMetrics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\LookoutforVision\LookoutforVisionClient createLookoutforVision(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionLookoutforVision(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MQ\MQClient createMQ(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMQ(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MTurk\MTurkClient createMTurk(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMTurk(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MWAA\MWAAClient createMWAA(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMWAA(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MachineLearning\MachineLearningClient createMachineLearning(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMachineLearning(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Macie\MacieClient createMacie(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMacie(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Macie2\Macie2Client createMacie2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMacie2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MainframeModernization\MainframeModernizationClient createMainframeModernization(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMainframeModernization(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ManagedBlockchain\ManagedBlockchainClient createManagedBlockchain(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionManagedBlockchain(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ManagedBlockchainQuery\ManagedBlockchainQueryClient createManagedBlockchainQuery(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionManagedBlockchainQuery(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ManagedGrafana\ManagedGrafanaClient createManagedGrafana(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionManagedGrafana(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MarketplaceCatalog\MarketplaceCatalogClient createMarketplaceCatalog(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMarketplaceCatalog(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MarketplaceCommerceAnalytics\MarketplaceCommerceAnalyticsClient createMarketplaceCommerceAnalytics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMarketplaceCommerceAnalytics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MarketplaceEntitlementService\MarketplaceEntitlementServiceClient createMarketplaceEntitlementService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMarketplaceEntitlementService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MarketplaceMetering\MarketplaceMeteringClient createMarketplaceMetering(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMarketplaceMetering(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaConnect\MediaConnectClient createMediaConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaConnect(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaConvert\MediaConvertClient createMediaConvert(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaConvert(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaLive\MediaLiveClient createMediaLive(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaLive(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaPackage\MediaPackageClient createMediaPackage(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaPackage(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaPackageV2\MediaPackageV2Client createMediaPackageV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaPackageV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaPackageVod\MediaPackageVodClient createMediaPackageVod(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaPackageVod(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaStore\MediaStoreClient createMediaStore(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaStore(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaStoreData\MediaStoreDataClient createMediaStoreData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaStoreData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MediaTailor\MediaTailorClient createMediaTailor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMediaTailor(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MedicalImaging\MedicalImagingClient createMedicalImaging(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMedicalImaging(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MemoryDB\MemoryDBClient createMemoryDB(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMemoryDB(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MigrationHub\MigrationHubClient createMigrationHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMigrationHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MigrationHubConfig\MigrationHubConfigClient createMigrationHubConfig(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMigrationHubConfig(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MigrationHubOrchestrator\MigrationHubOrchestratorClient createMigrationHubOrchestrator(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMigrationHubOrchestrator(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MigrationHubRefactorSpaces\MigrationHubRefactorSpacesClient createMigrationHubRefactorSpaces(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMigrationHubRefactorSpaces(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MigrationHubStrategyRecommendations\MigrationHubStrategyRecommendationsClient createMigrationHubStrategyRecommendations(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMigrationHubStrategyRecommendations(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Mobile\MobileClient createMobile(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionMobile(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Neptune\NeptuneClient createNeptune(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionNeptune(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Neptunedata\NeptunedataClient createNeptunedata(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionNeptunedata(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\NetworkFirewall\NetworkFirewallClient createNetworkFirewall(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionNetworkFirewall(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\NetworkManager\NetworkManagerClient createNetworkManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionNetworkManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\NimbleStudio\NimbleStudioClient createNimbleStudio(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionNimbleStudio(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\OAM\OAMClient createOAM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOAM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\OSIS\OSISClient createOSIS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOSIS(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Omics\OmicsClient createOmics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOmics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\OpenSearchServerless\OpenSearchServerlessClient createOpenSearchServerless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOpenSearchServerless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\OpenSearchService\OpenSearchServiceClient createOpenSearchService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOpenSearchService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\OpsWorks\OpsWorksClient createOpsWorks(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOpsWorks(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\OpsWorksCM\OpsWorksCMClient createOpsWorksCM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOpsWorksCM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Organizations\OrganizationsClient createOrganizations(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOrganizations(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Outposts\OutpostsClient createOutposts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionOutposts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PI\PIClient createPI(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPI(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Panorama\PanoramaClient createPanorama(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPanorama(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PaymentCryptography\PaymentCryptographyClient createPaymentCryptography(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPaymentCryptography(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PaymentCryptographyData\PaymentCryptographyDataClient createPaymentCryptographyData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPaymentCryptographyData(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PcaConnectorAd\PcaConnectorAdClient createPcaConnectorAd(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPcaConnectorAd(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Personalize\PersonalizeClient createPersonalize(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPersonalize(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PersonalizeEvents\PersonalizeEventsClient createPersonalizeEvents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPersonalizeEvents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PersonalizeRuntime\PersonalizeRuntimeClient createPersonalizeRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPersonalizeRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Pinpoint\PinpointClient createPinpoint(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPinpoint(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PinpointEmail\PinpointEmailClient createPinpointEmail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPinpointEmail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PinpointSMSVoice\PinpointSMSVoiceClient createPinpointSMSVoice(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPinpointSMSVoice(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PinpointSMSVoiceV2\PinpointSMSVoiceV2Client createPinpointSMSVoiceV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPinpointSMSVoiceV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Pipes\PipesClient createPipes(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPipes(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Polly\PollyClient createPolly(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPolly(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Pricing\PricingClient createPricing(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPricing(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PrivateNetworks\PrivateNetworksClient createPrivateNetworks(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPrivateNetworks(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\PrometheusService\PrometheusServiceClient createPrometheusService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionPrometheusService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Proton\ProtonClient createProton(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionProton(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\QLDB\QLDBClient createQLDB(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionQLDB(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\QLDBSession\QLDBSessionClient createQLDBSession(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionQLDBSession(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\QuickSight\QuickSightClient createQuickSight(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionQuickSight(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\RAM\RAMClient createRAM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRAM(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\RDSDataService\RDSDataServiceClient createRDSDataService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRDSDataService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Rds\RdsClient createRds(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRds(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\RecycleBin\RecycleBinClient createRecycleBin(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRecycleBin(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Redshift\RedshiftClient createRedshift(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRedshift(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\RedshiftDataAPIService\RedshiftDataAPIServiceClient createRedshiftDataAPIService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRedshiftDataAPIService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\RedshiftServerless\RedshiftServerlessClient createRedshiftServerless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRedshiftServerless(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Rekognition\RekognitionClient createRekognition(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRekognition(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ResilienceHub\ResilienceHubClient createResilienceHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionResilienceHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ResourceExplorer2\ResourceExplorer2Client createResourceExplorer2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionResourceExplorer2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ResourceGroups\ResourceGroupsClient createResourceGroups(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionResourceGroups(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ResourceGroupsTaggingAPI\ResourceGroupsTaggingAPIClient createResourceGroupsTaggingAPI(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionResourceGroupsTaggingAPI(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\RoboMaker\RoboMakerClient createRoboMaker(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRoboMaker(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\RolesAnywhere\RolesAnywhereClient createRolesAnywhere(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRolesAnywhere(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Route53\Route53Client createRoute53(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRoute53(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Route53Domains\Route53DomainsClient createRoute53Domains(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRoute53Domains(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Route53RecoveryCluster\Route53RecoveryClusterClient createRoute53RecoveryCluster(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRoute53RecoveryCluster(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Route53RecoveryControlConfig\Route53RecoveryControlConfigClient createRoute53RecoveryControlConfig(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRoute53RecoveryControlConfig(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Route53RecoveryReadiness\Route53RecoveryReadinessClient createRoute53RecoveryReadiness(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRoute53RecoveryReadiness(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Route53Resolver\Route53ResolverClient createRoute53Resolver(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionRoute53Resolver(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\S3\S3Client createS3(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\S3\S3MultiRegionClient createMultiRegionS3(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\S3Control\S3ControlClient createS3Control(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionS3Control(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\S3Outposts\S3OutpostsClient createS3Outposts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionS3Outposts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SSMContacts\SSMContactsClient createSSMContacts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSSMContacts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SSMIncidents\SSMIncidentsClient createSSMIncidents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSSMIncidents(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SSO\SSOClient createSSO(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSSO(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SSOAdmin\SSOAdminClient createSSOAdmin(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSSOAdmin(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SSOOIDC\SSOOIDCClient createSSOOIDC(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSSOOIDC(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SageMaker\SageMakerClient createSageMaker(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSageMaker(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SageMakerFeatureStoreRuntime\SageMakerFeatureStoreRuntimeClient createSageMakerFeatureStoreRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSageMakerFeatureStoreRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SageMakerGeospatial\SageMakerGeospatialClient createSageMakerGeospatial(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSageMakerGeospatial(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SageMakerMetrics\SageMakerMetricsClient createSageMakerMetrics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSageMakerMetrics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SageMakerRuntime\SageMakerRuntimeClient createSageMakerRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSageMakerRuntime(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SagemakerEdgeManager\SagemakerEdgeManagerClient createSagemakerEdgeManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSagemakerEdgeManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SavingsPlans\SavingsPlansClient createSavingsPlans(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSavingsPlans(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Scheduler\SchedulerClient createScheduler(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionScheduler(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Schemas\SchemasClient createSchemas(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSchemas(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SecretsManager\SecretsManagerClient createSecretsManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSecretsManager(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SecurityHub\SecurityHubClient createSecurityHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSecurityHub(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SecurityLake\SecurityLakeClient createSecurityLake(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSecurityLake(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ServerlessApplicationRepository\ServerlessApplicationRepositoryClient createServerlessApplicationRepository(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionServerlessApplicationRepository(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ServiceCatalog\ServiceCatalogClient createServiceCatalog(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionServiceCatalog(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ServiceDiscovery\ServiceDiscoveryClient createServiceDiscovery(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionServiceDiscovery(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ServiceQuotas\ServiceQuotasClient createServiceQuotas(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionServiceQuotas(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Ses\SesClient createSes(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSes(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SesV2\SesV2Client createSesV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSesV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Sfn\SfnClient createSfn(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSfn(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Shield\ShieldClient createShield(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionShield(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SimSpaceWeaver\SimSpaceWeaverClient createSimSpaceWeaver(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSimSpaceWeaver(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Sms\SmsClient createSms(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSms(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SnowBall\SnowBallClient createSnowBall(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSnowBall(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SnowDeviceManagement\SnowDeviceManagementClient createSnowDeviceManagement(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSnowDeviceManagement(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Sns\SnsClient createSns(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSns(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Sqs\SqsClient createSqs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSqs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Ssm\SsmClient createSsm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSsm(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SsmSap\SsmSapClient createSsmSap(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSsmSap(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\StorageGateway\StorageGatewayClient createStorageGateway(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionStorageGateway(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Sts\StsClient createSts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSts(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Support\SupportClient createSupport(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSupport(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\SupportApp\SupportAppClient createSupportApp(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSupportApp(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Swf\SwfClient createSwf(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSwf(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Synthetics\SyntheticsClient createSynthetics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionSynthetics(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Textract\TextractClient createTextract(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionTextract(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\TimestreamQuery\TimestreamQueryClient createTimestreamQuery(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionTimestreamQuery(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\TimestreamWrite\TimestreamWriteClient createTimestreamWrite(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionTimestreamWrite(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Tnb\TnbClient createTnb(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionTnb(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\TranscribeService\TranscribeServiceClient createTranscribeService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionTranscribeService(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Transfer\TransferClient createTransfer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionTransfer(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Translate\TranslateClient createTranslate(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionTranslate(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\VPCLattice\VPCLatticeClient createVPCLattice(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionVPCLattice(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\VerifiedPermissions\VerifiedPermissionsClient createVerifiedPermissions(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionVerifiedPermissions(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\VoiceID\VoiceIDClient createVoiceID(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionVoiceID(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WAFV2\WAFV2Client createWAFV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWAFV2(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\Waf\WafClient createWaf(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWaf(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WafRegional\WafRegionalClient createWafRegional(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWafRegional(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WellArchitected\WellArchitectedClient createWellArchitected(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWellArchitected(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WorkDocs\WorkDocsClient createWorkDocs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWorkDocs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WorkLink\WorkLinkClient createWorkLink(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWorkLink(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WorkMail\WorkMailClient createWorkMail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWorkMail(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WorkMailMessageFlow\WorkMailMessageFlowClient createWorkMailMessageFlow(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWorkMailMessageFlow(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WorkSpaces\WorkSpacesClient createWorkSpaces(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWorkSpaces(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\WorkSpacesWeb\WorkSpacesWebClient createWorkSpacesWeb(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionWorkSpacesWeb(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\XRay\XRayClient createXRay(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionXRay(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\drs\drsClient createdrs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegiondrs(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\finspace\finspaceClient createfinspace(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionfinspace(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\imagebuilder\imagebuilderClient createimagebuilder(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionimagebuilder(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\ivschat\ivschatClient createivschat(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionivschat(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\kendra\kendraClient createkendra(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionkendra(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\mgn\mgnClient createmgn(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionmgn(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\signer\signerClient createsigner(array $args = [])
 * @method \EDDAmazon\Vendor\Aws\MultiRegionClient createMultiRegionsigner(array $args = [])
 */
class Sdk
{
    const VERSION = '3.285.4';

    /** @var array Arguments for creating clients */
    private $args;

    /**
     * Constructs a new SDK object with an associative array of default
     * client settings.
     *
     * @param array $args
     *
     * @throws \InvalidArgumentException
     * @see EDDAmazon\Vendor\Aws\AwsClient::__construct for a list of available options.
     */
    public function __construct(array $args = [])
    {
        $this->args = $args;

        if (!isset($args['handler']) && !isset($args['http_handler'])) {
            $this->args['http_handler'] = default_http_handler();
        }
    }

    public function __call($name, array $args)
    {
        $args = isset($args[0]) ? $args[0] : [];
        if (strpos($name, 'createMultiRegion') === 0) {
            return $this->createMultiRegionClient(substr($name, 17), $args);
        }

        if (strpos($name, 'create') === 0) {
            return $this->createClient(substr($name, 6), $args);
        }

        throw new \BadMethodCallException("Unknown method: {$name}.");
    }

    /**
     * Get a client by name using an array of constructor options.
     *
     * @param string $name Service name or namespace (e.g., DynamoDb, s3).
     * @param array  $args Arguments to configure the client.
     *
     * @return AwsClientInterface
     * @throws \InvalidArgumentException if any required options are missing or
     *                                   the service is not supported.
     * @see EDDAmazon\Vendor\Aws\AwsClient::__construct for a list of available options for args.
     */
    public function createClient($name, array $args = [])
    {
        // Get information about the service from the manifest file.
        $service = manifest($name);
        $namespace = $service['namespace'];

        // Instantiate the client class.
        $client = "EDDAmazon\Vendor\Aws\\{$namespace}\\{$namespace}Client";
        return new $client($this->mergeArgs($namespace, $service, $args));
    }

    public function createMultiRegionClient($name, array $args = [])
    {
        // Get information about the service from the manifest file.
        $service = manifest($name);
        $namespace = $service['namespace'];

        $klass = "EDDAmazon\Vendor\Aws\\{$namespace}\\{$namespace}MultiRegionClient";
        $klass = class_exists($klass) ? $klass : MultiRegionClient::class;

        return new $klass($this->mergeArgs($namespace, $service, $args));
    }

    /**
     * Clone existing SDK instance with ability to pass an associative array
     * of extra client settings.
     *
     * @param array $args
     *
     * @return self
     */
    public function copy(array $args = [])
    {
        return new self($args + $this->args);
    }

    private function mergeArgs($namespace, array $manifest, array $args = [])
    {
        // Merge provided args with stored, service-specific args.
        if (isset($this->args[$namespace])) {
            $args += $this->args[$namespace];
        }

        // Provide the endpoint prefix in the args.
        if (!isset($args['service'])) {
            $args['service'] = $manifest['endpoint'];
        }

        return $args + $this->args;
    }

    /**
     * Determine the endpoint prefix from a client namespace.
     *
     * @param string $name Namespace name
     *
     * @return string
     * @internal
     * @deprecated Use the `\EDDAmazon\Vendor\Aws\manifest()` function instead.
     */
    public static function getEndpointPrefix($name)
    {
        return manifest($name)['endpoint'];
    }
}
